#!/bin/bash
echo yo

export STACK_NAME="portainer_stack"
export COMMAND=$1

function func_compose {
    echo Going $1 ...
    docker-compose -p ${STACK_NAME} -f ${STACK_NAME}/docker-compose.yml $1 $2
}

if [ "${COMMAND}" = "up" ]
then
    func_compose up -d
fi

if [ "${COMMAND}" = "down" ]
then
    func_compose down
fi

if [ "${COMMAND}" = "down" ]
then
    func_compose pull
fi
