version: "2"

services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    command: postgres -c 'shared_buffers=128MB' -c 'max_connections=100' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - database_net
    #network_mode: bridge
    mem_limit: 256M

#  elasticsearch:
#    image: elasticsearch:5.6
#    ports:
#    - "9200:9200"
#    - "9300:9300"
#    environment:
#    - discovery.type=single-node
#    networks:
#    - database_net
#    restart: always
#    mem_limit: 2048M

volumes:
    postgres_data:
    pgadmin_data:

networks:
  database_net:
    driver: bridge