version: "2"

services:
  postgres:
    image: postgres:9.5-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=20' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - database_net
    #network_mode: bridge
    mem_limit: 256M

#  elasticsearch:
#    image: elasticsearch:5.4.3
#    restart: 'no'
#    ports:
#    - "9200:9200"
#    - "9300:9300"
#    environment:
#    - discovery.type=single-node
#    - ES_JAVA_OPTS=-Xms1g -Xmx1g
#    volumes:
#    - elasticsearch_data:/usr/share/elasticsearch/data
#    networks:
#    - database_net
##    mem_limit: 1024M

volumes:
    postgres_data:
    elasticsearch_data:

networks:
  database_net:
    driver: bridge