version: "3"

services:
  postgres:
    image: postgres:9.6.15-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
#    command: postgres -c 'shared_buffers=${POSTGRES_BUFFER_SIZE}' -c 'max_connections=${POSTGRES_MAX_CONNECTIONS}' -c 'shared_preload_libraries=pg_stat_statements'
    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./initdb/00_pg_statements.sql:/docker-entrypoint-initdb.d/00_pg_statements.sql
    networks:
    - database-net

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
#    restart: 'no'
#    ports:
#    - "9200:9200"
#    - "9300:9300"
#    environment:
#    - discovery.type=single-node
#    - ES_JAVA_OPTS=-Xms1g -Xmx1g
#    volumes:
#    - elasticsearch_data:/usr/share/elasticsearch/data
#    networks:
#    - database-net
##    mem_limit: 1024M

volumes:
    postgres_data:
#    elasticsearch_data:

networks:
  database-net:
#    driver: bridge