version: "3"

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8000:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=postgres
    - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    networks:
    - pgadmin_net

volumes:
    pgadmin_data:

networks:
  pgadmin_net:
    driver: bridge