#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-world
#spec:
#  selector:
#    app: hello-world
#  ports:
#    - protocol: TCP
#      port: 8080
##      nodePort: 30001
#  type: NodePort

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
