#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-world
#spec:
#  selector:
#    app: hello-world
#  ports:
#    - protocol: TCP
#      port: 8080
##      nodePort: 30001
#  type: NodePort

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-exampleservice
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: spring-boot-exampleservice
          image: goafabric/spring-boot-exampleservice:1.0.0-SNAPSHOT
          ports:
            - containerPort: 50700
              protocol: TCP
