version: "2"

services:
  postgres:
    image: postgres:9.6-alpine
    #container_name: postgres_example_net
    #expose:
    #- "5432"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - database_net
    restart: always
    mem_limit: 256M

  pgadmin:
    image: dpage/pgadmin4
    #expose:
    #  - 80
    ports:
      - 8000:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=postgres
    - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    networks:
    - database_net
    restart: always
    mem_limit: 64M


volumes:
    postgres_data:
    pgadmin_data:

networks:
  database_net:
    driver: bridge