kind: Service
apiVersion: v1
metadata:
  name: spring-boot-exampleservice
spec:
  selector:
    app: spring-boot-exampleservice
  ports:
    - protocol: TCP
      port: 50700
      nodePort: 30100 #this is the external port
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-exampleservice
spec:
  selector:
    matchLabels:
      app: spring-boot-exampleservice
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-exampleservice
    spec:
      containers:
        - name: spring-boot-exampleservice
          image: goafabric/spring-boot-exampleservice:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 50700
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 50700
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 50700
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3