kind: Service
apiVersion: v1
metadata:
  name: spring-boot-exampleservice
spec:
  selector:
    app: spring-boot-exampleservice
  ports:
    - protocol: TCP
      port: 50700
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-exampleservice
spec:
  selector:
    matchLabels:
      app: spring-boot-exampleservice
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-exampleservice
    spec:
      containers:
        - name: spring-boot-exampleservice
          image: goafabric/spring-boot-exampleservice:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 50700